version: '3'
services:
        backend:
                build:
                        context: backend
                        dockerfile: Dockerfile
                expose:
                        - 80
                depends_on:
                        - database
        frontend:
                build:
                        context: frontend
                        dockerfile: Dockerfile
                ports:
                        - 80:80
                depends_on:
                        - backend
        database:
                image: mongo
                environment:
                        - MONGO_DATA_DIR=/data/db
                volumes: 
                        - ./data/db:/data/db
                expose: 
                        - 27017
                command: mongod --smallfiles
